# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElementarySchool', '0003_maharashtra_districts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maharashtra_districts',
            old_name='name_0',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='maharashtra_districts',
            old_name='name_1',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='maharashtra_districts',
            old_name='name_2',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='maharashtra_districts',
            old_name='name_3',
            new_name='taluka',
        ),
    ]
