# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.gis.db import models

class DistrictSummary(models.Model):
    distname = models.CharField(max_length=200, blank=True, null=True)
    distcode = models.BigIntegerField(blank=True, null=True)
    school = models.BigIntegerField(blank=True, null=True)
    teacher = models.BigIntegerField(blank=True, null=True)
    student = models.BigIntegerField(blank=True, null=True)
    toiletwater_b = models.BigIntegerField(blank=True, null=True)
    toiletwater_g = models.BigIntegerField(blank=True, null=True)
    toiletb_func = models.BigIntegerField(blank=True, null=True)
    urinals_b = models.BigIntegerField(blank=True, null=True)
    toiletg_func = models.BigIntegerField(blank=True, null=True)
    urinals_g = models.BigIntegerField(blank=True, null=True)
    handwash_count = models.BigIntegerField(blank=True, null=True)
    schcat_1 = models.BigIntegerField(blank=True, null=True)
    schcat_2 = models.BigIntegerField(blank=True, null=True)
    schcat_3 = models.BigIntegerField(blank=True, null=True)
    schcat_4 = models.BigIntegerField(blank=True, null=True)
    schcat_5 = models.BigIntegerField(blank=True, null=True)
    schcat_6 = models.BigIntegerField(blank=True, null=True)
    schcat_7 = models.BigIntegerField(blank=True, null=True)
    schcat_8 = models.BigIntegerField(blank=True, null=True)
    schcat_10 = models.BigIntegerField(blank=True, null=True)
    schcat_11 = models.BigIntegerField(blank=True, null=True)
    water_1 = models.BigIntegerField(blank=True, null=True)
    water_2 = models.BigIntegerField(blank=True, null=True)
    water_3 = models.BigIntegerField(blank=True, null=True)
    water_4 = models.BigIntegerField(blank=True, null=True)
    water_5 = models.BigIntegerField(blank=True, null=True)
    bndrywall_1 = models.BigIntegerField(blank=True, null=True)
    bndrywall_2 = models.BigIntegerField(blank=True, null=True)
    bndrywall_3 = models.BigIntegerField(blank=True, null=True)
    bndrywall_4 = models.BigIntegerField(blank=True, null=True)
    bndrywall_5 = models.BigIntegerField(blank=True, null=True)
    bndrywall_6 = models.BigIntegerField(blank=True, null=True)
    bndrywall_7 = models.BigIntegerField(blank=True, null=True)
    bndrywall_8 = models.BigIntegerField(blank=True, null=True)
    schmgt_1 = models.BigIntegerField(blank=True, null=True)
    schmgt_2 = models.BigIntegerField(blank=True, null=True)
    schmgt_3 = models.BigIntegerField(blank=True, null=True)
    schmgt_4 = models.BigIntegerField(blank=True, null=True)
    schmgt_5 = models.BigIntegerField(blank=True, null=True)
    schmgt_6 = models.BigIntegerField(blank=True, null=True)
    schmgt_7 = models.BigIntegerField(blank=True, null=True)
    schmgt_8 = models.BigIntegerField(blank=True, null=True)
    schmgt_97 = models.BigIntegerField(blank=True, null=True)
    schmgt_98 = models.BigIntegerField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'district_summary'

    def __str__(self):
        return self.distname

class BlockSummary(models.Model):
    distname = models.CharField(max_length=200, blank=True, null=True)
    distcode = models.BigIntegerField(blank=True, null=True)
    block_name = models.CharField(max_length=200, blank=True, null=True)
    blockcode = models.BigIntegerField(blank=True, null=True)
    school = models.BigIntegerField(blank=True, null=True)
    teacher = models.BigIntegerField(blank=True, null=True)
    student = models.BigIntegerField(blank=True, null=True)
    toiletwater_b = models.BigIntegerField(blank=True, null=True)
    toiletwater_g = models.BigIntegerField(blank=True, null=True)
    toiletb_func = models.BigIntegerField(blank=True, null=True)
    urinals_b = models.BigIntegerField(blank=True, null=True)
    toiletg_func = models.BigIntegerField(blank=True, null=True)
    urinals_g = models.BigIntegerField(blank=True, null=True)
    handwash_count = models.BigIntegerField(blank=True, null=True)
    schcat_1 = models.BigIntegerField(blank=True, null=True)
    schcat_2 = models.BigIntegerField(blank=True, null=True)
    schcat_3 = models.BigIntegerField(blank=True, null=True)
    schcat_4 = models.BigIntegerField(blank=True, null=True)
    schcat_5 = models.BigIntegerField(blank=True, null=True)
    schcat_6 = models.BigIntegerField(blank=True, null=True)
    schcat_7 = models.BigIntegerField(blank=True, null=True)
    schcat_8 = models.BigIntegerField(blank=True, null=True)
    schcat_10 = models.BigIntegerField(blank=True, null=True)
    schcat_11 = models.BigIntegerField(blank=True, null=True)
    water_1 = models.BigIntegerField(blank=True, null=True)
    water_2 = models.BigIntegerField(blank=True, null=True)
    water_3 = models.BigIntegerField(blank=True, null=True)
    water_4 = models.BigIntegerField(blank=True, null=True)
    water_5 = models.BigIntegerField(blank=True, null=True)
    bndrywall_1 = models.BigIntegerField(blank=True, null=True)
    bndrywall_2 = models.BigIntegerField(blank=True, null=True)
    bndrywall_3 = models.BigIntegerField(blank=True, null=True)
    bndrywall_4 = models.BigIntegerField(blank=True, null=True)
    bndrywall_5 = models.BigIntegerField(blank=True, null=True)
    bndrywall_6 = models.BigIntegerField(blank=True, null=True)
    bndrywall_7 = models.BigIntegerField(blank=True, null=True)
    bndrywall_8 = models.BigIntegerField(blank=True, null=True)
    schmgt_1 = models.BigIntegerField(blank=True, null=True)
    schmgt_2 = models.BigIntegerField(blank=True, null=True)
    schmgt_3 = models.BigIntegerField(blank=True, null=True)
    schmgt_4 = models.BigIntegerField(blank=True, null=True)
    schmgt_5 = models.BigIntegerField(blank=True, null=True)
    schmgt_6 = models.BigIntegerField(blank=True, null=True)
    schmgt_7 = models.BigIntegerField(blank=True, null=True)
    schmgt_8 = models.BigIntegerField(blank=True, null=True)
    schmgt_97 = models.BigIntegerField(blank=True, null=True)
    schmgt_98 = models.BigIntegerField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'block_summary'

    def __str__(self):
        return self.distname+" "+self.block_name

class VillageSummary(models.Model):
    distname = models.CharField(max_length=200, blank=True, null=True)
    distcode = models.BigIntegerField(blank=True, null=True)
    block_name = models.CharField(max_length=200, blank=True, null=True)
    blockcode = models.BigIntegerField(blank=True, null=True)
    village_name = models.CharField(max_length=200, blank=True, null=True)
    villagecode = models.BigIntegerField(blank=True, null=True)
    school = models.BigIntegerField(blank=True, null=True)
    teacher = models.BigIntegerField(blank=True, null=True)
    student = models.BigIntegerField(blank=True, null=True)
    toiletwater_b = models.BigIntegerField(blank=True, null=True)
    toiletwater_g = models.BigIntegerField(blank=True, null=True)
    toiletb_func = models.BigIntegerField(blank=True, null=True)
    urinals_b = models.BigIntegerField(blank=True, null=True)
    toiletg_func = models.BigIntegerField(blank=True, null=True)
    urinals_g = models.BigIntegerField(blank=True, null=True)
    handwash_count = models.BigIntegerField(blank=True, null=True)
    schcat_1 = models.BigIntegerField(blank=True, null=True)
    schcat_2 = models.BigIntegerField(blank=True, null=True)
    schcat_3 = models.BigIntegerField(blank=True, null=True)
    schcat_4 = models.BigIntegerField(blank=True, null=True)
    schcat_5 = models.BigIntegerField(blank=True, null=True)
    schcat_6 = models.BigIntegerField(blank=True, null=True)
    schcat_7 = models.BigIntegerField(blank=True, null=True)
    schcat_8 = models.BigIntegerField(blank=True, null=True)
    schcat_10 = models.BigIntegerField(blank=True, null=True)
    schcat_11 = models.BigIntegerField(blank=True, null=True)
    water_1 = models.BigIntegerField(blank=True, null=True)
    water_2 = models.BigIntegerField(blank=True, null=True)
    water_3 = models.BigIntegerField(blank=True, null=True)
    water_4 = models.BigIntegerField(blank=True, null=True)
    water_5 = models.BigIntegerField(blank=True, null=True)
    bndrywall_1 = models.BigIntegerField(blank=True, null=True)
    bndrywall_2 = models.BigIntegerField(blank=True, null=True)
    bndrywall_3 = models.BigIntegerField(blank=True, null=True)
    bndrywall_4 = models.BigIntegerField(blank=True, null=True)
    bndrywall_5 = models.BigIntegerField(blank=True, null=True)
    bndrywall_6 = models.BigIntegerField(blank=True, null=True)
    bndrywall_7 = models.BigIntegerField(blank=True, null=True)
    bndrywall_8 = models.BigIntegerField(blank=True, null=True)
    schmgt_1 = models.BigIntegerField(blank=True, null=True)
    schmgt_2 = models.BigIntegerField(blank=True, null=True)
    schmgt_3 = models.BigIntegerField(blank=True, null=True)
    schmgt_4 = models.BigIntegerField(blank=True, null=True)
    schmgt_5 = models.BigIntegerField(blank=True, null=True)
    schmgt_6 = models.BigIntegerField(blank=True, null=True)
    schmgt_7 = models.BigIntegerField(blank=True, null=True)
    schmgt_8 = models.BigIntegerField(blank=True, null=True)
    schmgt_97 = models.BigIntegerField(blank=True, null=True)
    schmgt_98 = models.BigIntegerField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'village_summary'

    def __str__(self):
        return self.distname+" "+self.block_name+" "+self.village_name