# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distname', models.CharField(blank=True, max_length=200, null=True)),
                ('block_name', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.BigIntegerField(blank=True, null=True)),
                ('teacher', models.BigIntegerField(blank=True, null=True)),
                ('student', models.BigIntegerField(blank=True, null=True)),
                ('toiletwater_b', models.BigIntegerField(blank=True, null=True)),
                ('toiletwater_g', models.BigIntegerField(blank=True, null=True)),
                ('toiletb_func', models.BigIntegerField(blank=True, null=True)),
                ('urinals_b', models.BigIntegerField(blank=True, null=True)),
                ('toiletg_func', models.BigIntegerField(blank=True, null=True)),
                ('urinals_g', models.BigIntegerField(blank=True, null=True)),
                ('schcat_1', models.BigIntegerField(blank=True, null=True)),
                ('schcat_2', models.BigIntegerField(blank=True, null=True)),
                ('schcat_3', models.BigIntegerField(blank=True, null=True)),
                ('schcat_4', models.BigIntegerField(blank=True, null=True)),
                ('schcat_5', models.BigIntegerField(blank=True, null=True)),
                ('schcat_6', models.BigIntegerField(blank=True, null=True)),
                ('schcat_7', models.BigIntegerField(blank=True, null=True)),
                ('schcat_8', models.BigIntegerField(blank=True, null=True)),
                ('schcat_10', models.BigIntegerField(blank=True, null=True)),
                ('schcat_11', models.BigIntegerField(blank=True, null=True)),
                ('water_1', models.BigIntegerField(blank=True, null=True)),
                ('water_2', models.BigIntegerField(blank=True, null=True)),
                ('water_3', models.BigIntegerField(blank=True, null=True)),
                ('water_4', models.BigIntegerField(blank=True, null=True)),
                ('water_5', models.BigIntegerField(blank=True, null=True)),
                ('bndrywall_1', models.BigIntegerField(blank=True, null=True)),
                ('bndrywall_2', models.BigIntegerField(blank=True, null=True)),
                ('bndrywall_3', models.BigIntegerField(blank=True, null=True)),
                ('bndrywall_4', models.BigIntegerField(blank=True, null=True)),
                ('bndrywall_5', models.BigIntegerField(blank=True, null=True)),
                ('bndrywall_6', models.BigIntegerField(blank=True, null=True)),
                ('bndrywall_7', models.BigIntegerField(blank=True, null=True)),
                ('bndrywall_8', models.BigIntegerField(blank=True, null=True)),
                ('schmgt_1', models.BigIntegerField(blank=True, null=True)),
                ('schmgt_2', models.BigIntegerField(blank=True, null=True)),
                ('schmgt_3', models.BigIntegerField(blank=True, null=True)),
                ('schmgt_4', models.BigIntegerField(blank=True, null=True)),
                ('schmgt_5', models.BigIntegerField(blank=True, null=True)),
                ('schmgt_6', models.BigIntegerField(blank=True, null=True)),
                ('schmgt_7', models.BigIntegerField(blank=True, null=True)),
                ('schmgt_8', models.BigIntegerField(blank=True, null=True)),
                ('schmgt_97', models.BigIntegerField(blank=True, null=True)),
                ('schmgt_98', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'summary_info',
                'managed': False,
            },
        ),
    ]
