# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_level', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summaryinfo',
            options={'managed': True},
        ),
    ]
