# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_level', '0002_auto_20180228_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryinfo',
            name='handwash_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
