# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_level', '0004_auto_20180302_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summaryinfo',
            options={'managed': True},
        ),
    ]
