# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_level', '0005_auto_20180302_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summaryinfo',
            options={'managed': False},
        ),
    ]
